inc:
  # Blog Information
  title:        "Cyph"
  subtitle:     "News from the most powerful encrypted messenger"
  cover_image:  blog-cover.png
  logo:         logo.png
  
  # Company information
  company:      Cyph
  url:          https://www.cyph.com/
  facebook:     pages/Cyph/299270843606014
  twitter:      cyph
  github:       cyph
  gplus:        '115480892967656365943'
  about_link:   https://www.cyph.com/about/
  
  # Product Information
  product_link: https://cyph.im/
  tagline:      "Completely private voice &amp; video chat"
  
  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname:  cyph
  
  # Sharing settings
  sharing:
    twitter:    true
    facebook:   true
    gplus:      true
    hn:         true
    
  
 # Analytics     
  analytics:
    google: true
      
      
  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  google_font: true
  
  # Setup your fonts, colors etc at _assets/stylesheets/main.scss

url:         https://www.cyph.com/blog
baseurl:     /blog
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     []
timezone:    nil
encoding:    utf-8

# Show future posts
future:      false
show_drafts: nil
limit_posts: 0
pygments:    true

relative_permalinks: true

permalink:     pretty
paginate_path: 'page:num'
paginate: 10

markdown:      maruku
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

excerpt_separator: ""

safe:        false
host:        0.0.0.0
port:        4000
lsi:         false

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

redcloth:
  hard_breaks: true

#
# jekyll-assets: see more at https://github.com/ixti/jekyll-assets
#
assets:

  dirname: assets
  baseurl: /blog/assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  js_compressor: uglifier
  css_compressor: sass
  cachebust: none
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: false
